### ISSUE TITLE
Incorrect colours and styles from git bash on Windows

### ISSUE THREAD

**Issue by olivif** [IonicaBizau/node-couleurs#15]
![image](https://cloud.githubusercontent.com/assets/7736961/11914135/9b2162a4-a677-11e5-8d92-ccf9402db2e0.png)

I will investigate how this can be made better for Windows and follow up on here :smiley:

**Comment by IonicaBizau** [comment]
@olivif Thanks! Should you have any questions, let me know! :grin:

**Comment by olivif** [comment]
So, after some quick investigations, here's what I found :smile: 

This line is the culprit to some of the windows issues 
```
, fg: ["\u001b[38;5;", "\u001b[39m"]
```
It seems like on windows cmd that string is interpreted differently. 

I made a quick [prototype](https://gist.github.com/olivif/68bc3ba6838e32bd2b6e) and it seems to work.  
![image](https://cloud.githubusercontent.com/assets/7736961/11918298/6dd5ce16-a72b-11e5-97c0-58fd3feeca8a.png)

It seems like node-couleurs supports any hex/rgb code, so we would probably need a way of mapping that to this list .. 

Also, it seems like this is a pretty solved problem on both [colors.js](https://github.com/Marak/colors.js) and [chalk](https://github.com/chalk/chalk).

**Comment by IonicaBizau** [comment]
@olivif :heart_eyes: 

Does Windows cmd support 256 colors like UNIX/Linux terminals do?
If that is so, I wonder if [`x256`](https://github.com/substack/node-x256) works smoothly on Windows.

From what I saw, `colors.js` and `chalk` don't support hex color input.

**Comment by IonicaBizau** [comment]
@olivif Any news on this?

**Comment by olivif** [comment]
I had a look,  x256 doesn't work very well on windows either :frowning:

**Comment by IonicaBizau** [comment]
I'm on it. :rocket:

**Comment by IonicaBizau** [comment]
:ship: `6.0.0` :tada:  /cc #17 

Using [`ansy`](https://github.com/IonicaBizau/ansy), we try to get the best support for the rgb/hex colors, in this order: 16m colors, 256 colors, 16 colors, no colors. :joy:

**Comment by olivif** [comment]
@IonicaBizau great stuff! much better

![image](https://cloud.githubusercontent.com/assets/7736961/13469439/ae478e52-e0a7-11e5-9377-c14ed5acf5a6.png)

**Comment by IonicaBizau** [comment]
@olivif For posterity: the Windows command prompt does *not* support 256 colors. It supports only 16 colors. I'm wondering how the new version of [`image-to-ascii`](https://github.com/IonicaBizau/image-to-ascii) (currently in the `lwip` branch) works in Windows cmd. :smile:

**Comment by olivif** [comment]
is it using sh? 

![image](https://cloud.githubusercontent.com/assets/7736961/13469983/06477386-e0aa-11e5-8e31-a1ac5ee50a0e.png)

**Comment by olivif** [comment]
`npm install imgpx` fails miserably on my windows machine, I think I have a newer version of the cpp compiler and it really doesn't like it. So I wasn't able to try it :smile:

**Comment by IonicaBizau** [comment]
@olivif Do you have Visual Studio 2013 on your machine? I guess `lwip` fails to be compiled.

**Comment by olivif** [comment]
Yes, that is the issue. It's because I only have 2015 installed.

**Comment by IonicaBizau** [comment]
@olivif Well, it aims to work with Visual Studio >= 2013. I'm thinking that maybe I should do it in the reverse way: if GraphicsMagic is not installed, then try to compile and use `lwip`. :grin:

**Comment by olivif** [comment]
that could work :smile:

**Comment by IonicaBizau** [comment]
@olivif I did it! There we go: 

![](http://i.imgur.com/bruQd2e.jpg?1)

Don't forget to tell Microsoft to enable 16 million colors in Command Prompt. :joy: 

Here's how it works: [`lwipify`](https://github.com/IonicaBizau/lwipify) uses [`lwip2`](https://github.com/IonicaBizau/lwip2). `lwip2` checks if [GM is installed](https://github.com/IonicaBizau/gm-installed) and if not it tries to install `lwip`. 

[`image-parser`](https://github.com/IonicaBizau/image-parser) takes care of parsing the image (using `lwip` or `gm`, doesn't matter).

**Comment by olivif** [comment]
niiiiiice!!! :smile:
